substitutions:
# Unique name for this configuration — use only lowercase letters and numbers,
# no spaces or special characters, e.g. "tclac".
# If you have multiple climate modules, change device_name accordingly,
# e.g. by appending numbers: tclac1, tclac2, tclac3...
  device_name: tclac
# Human-readable name for the climate device, shown in the UI:
  humanly_name: TCL Air Conditioner
# WiFi credentials — can alternatively be stored in the "secret" file in ESPHome, otherwise edit here:
# WiFi network name:
  wifi_ssid: !secret wifi_ssid
# WiFi password:
  wifi_password: !secret wifi_password
# Recovery mode password — the hotspot will be named: "{device_name} Fallback Hotspot"
  recovery_pass: mKSzmBdt7DAj
# OTA update password — generated once and used permanently:
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
# API key for connecting to Home Assistant — generate a new key here: https://esphome.io/components/api.html
  api_key: lmUoWsWs1oqSfJqLFsA6PisHSx4Y1G+iu7V3PDIqpXk=
# GPIO pins on the module where UART is connected:
  uart_rx: GPIO3
  uart_tx: GPIO1
# GPIO pins for status LEDs (receive/transmit). Only work if "leds" is enabled in "packages".
# If you don't want to use LEDs, you can enter any values here.
  receive_led: GPIO6
  transmit_led: GPIO4

# Included files — automatically downloaded from the internet and updated.
# Uncomment the options you want.
# Description of options:
# - packages/leds.yaml — LEDs to indicate transmit/receive; pins defined via receive_led / transmit_led
#
# All lines must be at exactly this indentation level — otherwise errors will occur!
packages:
  remote_package:
    url: https://github.com/jonathanendersby/tclac-en.git
    ref: master
    files:
    # v — lines must be aligned exactly here, otherwise problems!
      - packages/core.yaml # The core of the whole thing
      # - packages/leds.yaml
    refresh: 30s

# Selected module to be flashed with this firmware.
# Pre-made configurations can be used by removing the comment:

# ESP-01S
esp8266:
  board: esp01_1m

# Hommyn HDN/WFN-02-01
#esp32:
#  board: esp32-c3-devkitm-1
#  framework:
#    type: arduino

# Status LED — optionally enable if free pins are available
#status_led:
#  pin:
#    number: GPIO5
#    inverted: false
